version: '3'

services:
  booking:
    build: .
    depends_on:
      - 'database'
    ports: 
      - '80:3002'

  database:
    image: mongo:latest
  
  mongo-seed:
    build: ./database
    depends_on:
      - 'database'